force-app/main/default/objects/OrderItem__c/OrderItem__c.object-meta.xml
<CustomObject>
    <label>OrderItem</label>
    <nameField>
        <label>OrderItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrderItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderItem__c/fields/OrderId__c.field-meta.xml
<CustomField>
    <fullName>OrderId__c</fullName>
    <label>OrderId</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>OrderItems</relationshipLabel>
    <relationshipName>OrderItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <label>ProductId</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>OrderItems</relationshipLabel>
    <relationshipName>OrderItems</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/OrderItemService.cls
public class OrderItemService {


	public static void createOrderItems(Map<Id, Integer> productsQuantities, Id orderId){
		List<OrderItem__c> orderItems = new List<OrderItem__c>();
		Set<ID> productIds = productsQuantities.keySet();

		for (ID productId : productIds){
			OrderItem__c orderItem = new OrderItem__c();
			orderItem.ProductId__c = productId;
			orderItem.Quantity__c = productsQuantities.get(productId);
			orderItem.OrderId__c = orderId;
			orderItems.add(orderItem);
		}

		insert orderItems;
	}
}