force-app/main/default/objects/Product__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <label>Family</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Family 1</fullName>
            </value>
            <value>
                <fullName>Family 2</fullName>
            </value>
            <value>
                <fullName>Family 3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Image__c.field-meta.xml
<CustomField>
    <fullName>Image__c</fullName>
    <description>Link to image</description>
    <label>Image</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Electronics</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Food</fullName>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OrderManagerController.cls
public with sharing class OrderManagerController {

	@AuraEnabled(cacheable = true)
	public static List<Product__c> getFilteredProducts(String filterType,
													   String filterFamily) {

		Boolean hasFilterType = !(filterType == null || filterType =='');
		Boolean hasFilterFamily = !(filterFamily == null || filterFamily =='');

		List<Product__c> products = new List<Product__c>();

		if(hasFilterType && hasFilterFamily) {
		products =	[
					SELECT ID, Name, Type__c, Family__c, Description__c, Price__c, Image__c
					FROM Product__c
					WHERE Type__c=:filterType AND Family__c=:filterFamily
					WITH SECURITY_ENFORCED
					LIMIT 40
			];
		} else if (!hasFilterType && hasFilterFamily) {
			products =	[
					SELECT ID, Name, Type__c, Family__c, Description__c, Price__c, Image__c
					FROM Product__c
					WHERE Family__c=:filterFamily
					WITH SECURITY_ENFORCED
					LIMIT 40
			];

		} else if (hasFilterType && !hasFilterFamily){
			products = [
					SELECT ID, Name, Type__c, Family__c, Description__c, Price__c, Image__c
					FROM Product__c
					WHERE Type__c=:filterType
					WITH SECURITY_ENFORCED
					LIMIT 40
			];
		} else {
			products = [
					SELECT ID, Name, Type__c, Family__c, Description__c, Price__c, Image__c
					FROM Product__c
					WITH SECURITY_ENFORCED
					LIMIT 40
			];
		}
		return products;
	}
}