force-app/main/default/objects/Product__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <label>Family</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Family 1</fullName>
            </value>
            <value>
                <fullName>Family 2</fullName>
            </value>
            <value>
                <fullName>Family 3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Electronics</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Food</fullName>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OrderManagerControllerTest.cls
@isTest
public class OrderManagerControllerTest {
	private class RestMock implements HttpCalloutMock {
		public HTTPResponse respond(HTTPRequest req)
			{
				HttpResponse res = new HttpResponse();
				res.setHeader('Content-Type', 'application/json');
				res.setBody('{"success": true, "word": "ololotrololo", "rowcount": 0, "data": [], "errormessage": ""}');
				res.setStatusCode(200);
				return res;
			}
	}

	@isTest
	static void getFilteredProductsReturnsCorrectValueWhenTwoFiltersAreSet() {
		Test.setMock(HttpCalloutMock.class, new RestMock());

		Product__c product = new Product__c();
		product.Type__c = 'Electronics';
		product.Family__c = 'Cheap';
		product.Price__c = 1;
		insert product;
		List< Product__c > products = OrderManagerController.getFilteredProducts('Electronics', 'Cheap');
		System.assertEquals(1, products.size());
		System.assertEquals(product.Id, products.get(0).Id);
	}

	@isTest
	static void getFilteredProductsReturnsCorrectValueWhenOnlyFamilyFilterIsSet() {
		Test.setMock(HttpCalloutMock.class, new RestMock());

		Product__c product = new Product__c();
		product.Type__c = 'Electronics';
		product.Family__c = 'Cheap';
		product.Price__c = 1;

		insert product;

		List< Product__c > products = OrderManagerController.getFilteredProducts('', 'Cheap');
		System.assertEquals(1, products.size());
		System.assertEquals(product.Id, products.get(0).Id);
	}

	@isTest
	static void getFilteredProductsReturnsCorrectValueWhenOnlyTypeFilterIsSet() {
		Test.setMock(HttpCalloutMock.class, new RestMock());

		Product__c product = new Product__c();
		product.Type__c = 'Electronics';
		product.Family__c = 'Cheap';
		product.Price__c = 1;

		insert product;

		List< Product__c > products = OrderManagerController.getFilteredProducts('Electronics', '');
		System.assertEquals(1, products.size());
		System.assertEquals(product.Id, products.get(0).Id);
	}

	@isTest
	static void getFilteredProductsReturnsCorrectValueWhenNoFiltersAreSet() {
		Test.setMock(HttpCalloutMock.class, new RestMock());

		Product__c product = new Product__c();
		product.Type__c = 'Electronics';
		product.Family__c = 'Cheap';
		product.Price__c = 1;

		insert product;

		List< Product__c > products = OrderManagerController.getFilteredProducts('', '');
		System.assertEquals(1, products.size());
		System.assertEquals(product.Id, products.get(0).Id);
	}
}