force-app/main/default/objects/Order__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AccountId</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OrderService.cls
public class OrderService {

	@AuraEnabled
	public static ID createOrder(String accountIdString, List<Map<String, Object>> cart){
		List<ID> productIds = new List<Id>();
		Map<ID, Integer> productsQuantities = new Map<Id, Integer>();
		ID accountId = (ID) accountIdString;

		for(Map<String, Object> cartItem : cart){
			ID productId =  (ID) cartItem.get('id');
			Integer productQuantity = Integer.valueOf(cartItem.get('quantity'));
			productIds.add(productId);
			productsQuantities.put(productId, productQuantity);
		}

		Order__c order = new Order__c();
		order.AccountId__c = accountId;
		insert order;

		ID orderId = order.Id;
		OrderItemService.createOrderItems(productsQuantities, orderId);

		return orderId;
	}

}