force-app/main/default/objects/Order__c/fields/TotalPrice__c.field-meta.xml
<CustomField>
    <fullName>TotalPrice__c</fullName>
    <label>TotalPrice</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/TotalProductCount__c.field-meta.xml
<CustomField>
    <fullName>TotalProductCount__c</fullName>
    <label>TotalProductCount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/OrderItem__c.object-meta.xml
<CustomObject>
    <label>OrderItem</label>
    <nameField>
        <label>OrderItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrderItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderItem__c/fields/OrderId__c.field-meta.xml
<CustomField>
    <fullName>OrderId__c</fullName>
    <label>OrderId</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>OrderItems</relationshipLabel>
    <relationshipName>OrderItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <label>ProductId</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>OrderItems</relationshipLabel>
    <relationshipName>OrderItems</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/OrderItemTriggerHandler.cls
public class OrderItemTriggerHandler {


	public static void populateOrderItemPriceField(List<OrderItem__c> records) {

		List<Id> productIds = new List<Id>();

		for (OrderItem__c orderItem : records) {
			productIds.add(orderItem.ProductId__c);
		}

		List<Product__c> products = [
				SELECT id, Price__c
				FROM Product__c
				WHERE Id IN :productIds
		];

		for (OrderItem__c orderItem : records) {
			Product__c orderItemProduct = null;
			for (Product__c product : products) {
				if (product.Id == orderItem.ProductId__c) {
					orderItemProduct = product;
					break;
				}
			}

			if (orderItem.Price__c == null) {
				orderItem.Price__c = orderItemProduct.Price__c;
			} else {
				orderItem.Price__c += orderItemProduct.Price__c;
			}

		}
	}

	public static void populateOrderTotalFields(List<OrderItem__c> records) {
		Decimal totalProductCount = 0;
		Decimal totalPrice = 0;

		for (OrderItem__c orderItem : records) {
			Decimal quantity = (Decimal) orderItem.get('Quantity__c');
			Decimal pricePerUnit = (Decimal) orderItem.get('Price__c');
			Decimal price = 0;
			if (quantity != null && pricePerUnit != null) {
				price = quantity * pricePerUnit;
			}
			totalProductCount = totalProductCount + quantity;
			totalPrice = totalPrice + price;
		}

		ID orderId = (ID) records.get(0).get('OrderId__c');

		Order__c order = [
				SELECT ID, TotalPrice__c, TotalProductCount__c
				FROM Order__c
				WHERE Id = :orderId
				WITH SECURITY_ENFORCED
				LIMIT 1
		];

		order.TotalPrice__c = totalPrice;
		order.TotalProductCount__c = totalProductCount;

		update order;
	}
}